# Generated by Django 3.2.12 on 2022-04-05 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
            ],
            options={
                'verbose_name': '1. Курс',
                'verbose_name_plural': '1. Курсы',
            },
        ),
        migrations.CreateModel(
            name='CoursePersonalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, help_text='Лекция завершена?', verbose_name='Завершен')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to='course_API.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '3. Курс(Прогресс)',
                'verbose_name_plural': '3. Курс(Прогресс)',
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название блока')),
                ('order', models.IntegerField(verbose_name='Порядковый номер лекции')),
                ('content', models.TextField(help_text='Текст лекции', verbose_name='Лекция')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='course_API.course')),
            ],
            options={
                'verbose_name': '1.2 Лекция',
                'verbose_name_plural': '1.2 Лекции',
                'unique_together': {('order', 'course')},
            },
        ),
        migrations.CreateModel(
            name='PresetMappedOptionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '2.3 Группа для вопросов с сопоставлением',
                'verbose_name_plural': '2.3 Группы для вопросов с сопоставлением',
            },
        ),
        migrations.CreateModel(
            name='QuestionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': '1.3 Тип вопроса',
                'verbose_name_plural': '1.3 Типы вопросов',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Текст вопроса', max_length=255, verbose_name='Вопрос')),
                ('order', models.IntegerField(blank=True, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='course_API.lesson')),
                ('type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='course_API.questiontype')),
            ],
            options={
                'verbose_name': '1.3 Вопрос к блоку',
                'verbose_name_plural': '1.3 Вопросы к блокам',
            },
        ),
        migrations.CreateModel(
            name='PresetMappedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_API.presetmappedoptiongroup')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapped_preset_options', to='course_API.question')),
            ],
            options={
                'verbose_name': '2.2 Вариант ответа с сопоставлением',
                'verbose_name_plural': '2.2 Варианты ответов с сопоставлением',
            },
        ),
        migrations.CreateModel(
            name='PresetChoosableOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('correct_answer', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_options', to='course_API.question')),
            ],
            options={
                'verbose_name': '2.1 Вариант ответа к вопросу',
                'verbose_name_plural': '2.1 Варианты ответов к вопросу',
            },
        ),
        migrations.CreateModel(
            name='PresetAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('boolean', models.BooleanField(blank=True, null=True)),
                ('mapped_answers', models.ManyToManyField(blank=True, to='course_API.PresetMappedOption')),
                ('options', models.ManyToManyField(blank=True, to='course_API.PresetChoosableOption')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preset_answers', to='course_API.question')),
            ],
            options={
                'verbose_name': '2. Задуманный ответ',
                'verbose_name_plural': '2. Задуманные ответы',
            },
        ),
        migrations.CreateModel(
            name='MappedAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=64)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course_API.presetmappedoptiongroup')),
            ],
            options={
                'verbose_name': '4.1 Ответ с сопоставлением',
                'verbose_name_plural': '4.1 Ответы с сопоставлением',
            },
        ),
        migrations.CreateModel(
            name='LessonPersonalProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('lesson_part_completed', models.BooleanField(default=False, help_text='Лекция изучена?', verbose_name='Теоретическая часть')),
                ('test_part_completed', models.BooleanField(default=False, help_text='Тест пройден?', verbose_name='Тест')),
                ('course_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='course_API.coursepersonalprogress')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='course_API.lesson')),
            ],
            options={
                'verbose_name': '3.1 Лекция(Прогресс)',
                'verbose_name_plural': '3.1 Лекция(Прогресс)',
                'unique_together': {('course_progress', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True)),
                ('boolean', models.BooleanField(blank=True, null=True)),
                ('lesson_progress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userAnswers', to='course_API.lessonpersonalprogress')),
                ('mapped_answers', models.ManyToManyField(blank=True, to='course_API.MappedAnswer')),
                ('multi_answers', models.ManyToManyField(blank=True, to='course_API.PresetChoosableOption')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userAnswers', to='course_API.question')),
                ('single_answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respondentChoosing', to='course_API.presetchoosableoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '4. Ответ пользователя',
                'verbose_name_plural': '4. Ответы пользователей',
                'unique_together': {('question', 'user')},
            },
        ),
    ]
