# Generated by Django 3.2.12 on 2022-04-02 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название курса')),
                ('premium', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LearningBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название блока')),
                ('order_priority', models.IntegerField(blank=True, null=True, verbose_name='Приоритет внутри курса')),
                ('content', models.TextField(help_text='Текст лекции', verbose_name='Лекция')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lession_app.lessoncourse')),
            ],
            options={
                'verbose_name': 'Блок обучения',
                'verbose_name_plural': 'Блоки обучения',
                'unique_together': {('course', 'order_priority')},
            },
        ),
    ]
